### ISSUE TITLE
setting queryingDisabled after config is set

### ISSUE THREAD

**Issue by eric-personal** [TriplyDB/Yasgui#204] opened 2022-07-14 03:52 UTC
Is there a way to set queryingDisabled after Yasgui instantiation. 
I'm looking for a way to disable submit of query while the query response is waiting to be returned. 
I tried to reset the queryingDisabled property example: 

`yasgui.config.yasqe.queryingDisabled = true;`

The only way the above line seems to work is durning Yasgui instantiation. 

I know I can set pointer-events: none; on the container element but anyone can turn this back on via dev tools. I'm trying to prevent multiple calls to the submit query until the first submit was successful. 

thanks!

**Comment by GerwinBosch** [comment] 2022-07-14 08:05
Hello @eric-personal,

One possible way of doing this is using Yasqe's event system:

```ts
yasgui.on("query", (_yasgui,tab) => tab.yasqe.config.queryingDisabled=true);
yasgui.on("queryResponse", (_yasgui,tab) => {
  tab.yasqe.config.queryingDisabled=false;
  tab.yasqe.drawButtons();
});
```

**Comment by GerwinBosch** [comment] 2022-07-27 08:12
I am closing this issue as I interpret the emoji's to mean that the issue is resolved

**Closed by GerwinBosch** 2022-07-27 08:12 UTC

**Comment by eric-personal** [comment] 2022-07-27 14:10
Yes thank you your solution was perfect.
